package model;
// Generated Feb 19, 2021 2:44:15 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Identity generated by hbm2java
 */
@Entity
@Table(name="identity"
    ,catalog="hirwa1"
)
public class Identity  implements java.io.Serializable {


     private int id;
     private String name;

    public Identity() {
    }

	
    public Identity(int id) {
        this.id = id;
    }
    public Identity(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


