/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myscientificcalculator;

/**
 *
 * @author HIRWA Jean Eric
 */
public class MyScCalculator extends javax.swing.JFrame {
    
    /**
     * Bellow are variable we shall use in creating the simple arithmetic 
     * operators like plus, minus, division, and multiplication since they 
     * require two numbers to work.
     */
    double first;
    double second;
    double result;
    String operation;
    String answer;
    /**
     * Creates new form MyScCalculator
     */
    public MyScCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        percentgButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultField = new javax.swing.JTextField();
        root = new javax.swing.JButton();
        eExponent = new javax.swing.JButton();
        Sinis = new javax.swing.JButton();
        Cosinis = new javax.swing.JButton();
        tangent = new javax.swing.JButton();
        TanOfh = new javax.swing.JButton();
        oneOverx = new javax.swing.JButton();
        logarithm = new javax.swing.JButton();
        sinOfh = new javax.swing.JButton();
        cosinOfh = new javax.swing.JButton();
        additionSign = new javax.swing.JButton();
        xPowery = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        BackSpace = new javax.swing.JButton();
        substractionSign = new javax.swing.JButton();
        xPower3 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        multiplicationSign = new javax.swing.JButton();
        xPower2 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        equalSign = new javax.swing.JButton();
        plusOrminus = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        divisionSign = new javax.swing.JButton();
        factorial = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jButton36.setText("jButton1");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setText("jButton1");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.setText("jButton1");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setText("jButton1");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setText("jButton1");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setText("jButton1");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButton42.setText("jButton1");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        jButton43.setText("jButton1");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });

        jButton44.setText("jButton1");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        jButton45.setText("jButton1");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });

        percentgButton.setText("%");
        percentgButton.setEnabled(false);
        percentgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentgButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Standard Calculator");

        resultField.setBackground(new java.awt.Color(204, 204, 255));
        resultField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFieldActionPerformed(evt);
            }
        });

        root.setText("Sqrt");
        root.setToolTipText("");
        root.setEnabled(false);
        root.setName(""); // NOI18N
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });

        eExponent.setText("e^x");
        eExponent.setEnabled(false);
        eExponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eExponentActionPerformed(evt);
            }
        });

        Sinis.setText("Sin");
        Sinis.setEnabled(false);
        Sinis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinisActionPerformed(evt);
            }
        });

        Cosinis.setText("Cos");
        Cosinis.setEnabled(false);
        Cosinis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosinisActionPerformed(evt);
            }
        });

        tangent.setText("Tan");
        tangent.setEnabled(false);
        tangent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tangentActionPerformed(evt);
            }
        });

        TanOfh.setText("Tanh");
        TanOfh.setEnabled(false);
        TanOfh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanOfhActionPerformed(evt);
            }
        });

        oneOverx.setText("1/x");
        oneOverx.setEnabled(false);
        oneOverx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneOverxActionPerformed(evt);
            }
        });

        logarithm.setText("Log");
        logarithm.setEnabled(false);
        logarithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarithmActionPerformed(evt);
            }
        });

        sinOfh.setText("Sinh");
        sinOfh.setEnabled(false);
        sinOfh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinOfhActionPerformed(evt);
            }
        });

        cosinOfh.setText("Cosh");
        cosinOfh.setEnabled(false);
        cosinOfh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosinOfhActionPerformed(evt);
            }
        });

        additionSign.setBackground(new java.awt.Color(204, 204, 204));
        additionSign.setText("+");
        additionSign.setEnabled(false);
        additionSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionSignActionPerformed(evt);
            }
        });

        xPowery.setText("x^y");
        xPowery.setEnabled(false);
        xPowery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPoweryActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setEnabled(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        BackSpace.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackSpace.setText("Back");
        BackSpace.setEnabled(false);
        BackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackSpaceActionPerformed(evt);
            }
        });

        substractionSign.setBackground(new java.awt.Color(204, 204, 204));
        substractionSign.setText("-");
        substractionSign.setEnabled(false);
        substractionSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractionSignActionPerformed(evt);
            }
        });

        xPower3.setText("x^3");
        xPower3.setEnabled(false);
        xPower3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPower3ActionPerformed(evt);
            }
        });

        num7.setBackground(new java.awt.Color(153, 153, 0));
        num7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num7.setText("7");
        num7.setEnabled(false);
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setBackground(new java.awt.Color(153, 153, 0));
        num8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num8.setText("8");
        num8.setEnabled(false);
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(153, 153, 0));
        num9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num9.setText("9");
        num9.setEnabled(false);
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        multiplicationSign.setBackground(new java.awt.Color(204, 204, 204));
        multiplicationSign.setText("*");
        multiplicationSign.setEnabled(false);
        multiplicationSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationSignActionPerformed(evt);
            }
        });

        xPower2.setText("x^2");
        xPower2.setEnabled(false);
        xPower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPower2ActionPerformed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(153, 153, 0));
        num4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num4.setText("4");
        num4.setEnabled(false);
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(153, 153, 0));
        num5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num5.setText("5");
        num5.setEnabled(false);
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(153, 153, 0));
        num6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num6.setText("6");
        num6.setEnabled(false);
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        equalSign.setBackground(new java.awt.Color(204, 204, 204));
        equalSign.setText("=");
        equalSign.setEnabled(false);
        equalSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalSignActionPerformed(evt);
            }
        });

        plusOrminus.setText("+/-");
        plusOrminus.setEnabled(false);
        plusOrminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusOrminusActionPerformed(evt);
            }
        });

        num0.setBackground(new java.awt.Color(153, 153, 0));
        num0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num0.setText("0");
        num0.setEnabled(false);
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        dot.setBackground(new java.awt.Color(153, 153, 0));
        dot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dot.setText(".");
        dot.setEnabled(false);
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        divisionSign.setBackground(new java.awt.Color(204, 204, 204));
        divisionSign.setText("/");
        divisionSign.setEnabled(false);
        divisionSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionSignActionPerformed(evt);
            }
        });

        factorial.setText("n!");
        factorial.setEnabled(false);
        factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialActionPerformed(evt);
            }
        });

        num1.setBackground(new java.awt.Color(153, 153, 0));
        num1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num1.setText("1");
        num1.setEnabled(false);
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(153, 153, 0));
        num2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num2.setText("2");
        num2.setEnabled(false);
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(153, 153, 0));
        num3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num3.setText("3");
        num3.setEnabled(false);
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("On");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Off");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xPower2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(multiplicationSign, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(xPowery, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(logarithm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(additionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(xPower3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(substractionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(plusOrminus, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(equalSign, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(resultField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(oneOverx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sinOfh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cosinOfh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sinis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cosinis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tangent, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TanOfh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sinis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cosinis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tangent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TanOfh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneOverx, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinOfh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cosinOfh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xPowery, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logarithm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xPower3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substractionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xPower2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationSign, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionSign, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plusOrminus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(equalSign, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        root.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultFieldActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
        // TODO add your handling code here:
        double a = Math.sqrt(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_rootActionPerformed

    private void eExponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eExponentActionPerformed
        // TODO add your handling code here:
        double a = Math.exp(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_eExponentActionPerformed

    private void SinisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinisActionPerformed
        // TODO add your handling code here:
        double a = Math.sin(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_SinisActionPerformed

    private void CosinisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosinisActionPerformed
        // TODO add your handling code here:
        double a = Math.cos(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_CosinisActionPerformed

    private void tangentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tangentActionPerformed
        // TODO add your handling code here:
        double a = Math.tan(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
        
    }//GEN-LAST:event_tangentActionPerformed

    private void TanOfhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanOfhActionPerformed
        // TODO add your handling code here:
        double a = Math.tanh(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_TanOfhActionPerformed

    private void oneOverxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneOverxActionPerformed
        // TODO add your handling code here:
        double a = 1/(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_oneOverxActionPerformed

    private void logarithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarithmActionPerformed
        // TODO add your handling code here:
        double a = Math.log(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_logarithmActionPerformed

    private void sinOfhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinOfhActionPerformed
        // TODO add your handling code here:
        double a = Math.sinh(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_sinOfhActionPerformed

    private void cosinOfhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosinOfhActionPerformed
        // TODO add your handling code here:
        double a = Math.cosh(Double.parseDouble(resultField.getText()));
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_cosinOfhActionPerformed

    private void additionSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionSignActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(resultField.getText());
        resultField.setText("");
        operation="+";
    }//GEN-LAST:event_additionSignActionPerformed

    private void xPoweryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPoweryActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(resultField.getText());
        resultField.setText("");
        operation="X^Y";
    }//GEN-LAST:event_xPoweryActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        resultField.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void BackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackSpaceActionPerformed
        // TODO add your handling code here:
        String backspace=null;
        if(resultField.getText().length()>0){
            StringBuilder str = new StringBuilder(resultField.getText());
            str.deleteCharAt(resultField.getText().length()-1);
            backspace = str.toString();
            resultField.setText(backspace);
        }
    }//GEN-LAST:event_BackSpaceActionPerformed

    private void substractionSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractionSignActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(resultField.getText());
        resultField.setText("");
        operation="-";
    }//GEN-LAST:event_substractionSignActionPerformed

    private void xPower3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPower3ActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(resultField.getText());
        a = a*a*a;
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
    }//GEN-LAST:event_xPower3ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num7.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num8.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num9.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num9ActionPerformed

    private void multiplicationSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationSignActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(resultField.getText());
        resultField.setText("");
        operation="*";
    }//GEN-LAST:event_multiplicationSignActionPerformed

    private void xPower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPower2ActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(resultField.getText());
        a = a*a;
        resultField.setText("");
        resultField.setText(resultField.getText()+a);
        
    }//GEN-LAST:event_xPower2ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num4.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num5.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num6.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num6ActionPerformed

    private void equalSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalSignActionPerformed
        // TODO add your handling code here:
        second = Double.parseDouble(resultField.getText());
        if (operation == "+"){
            result = first + second;
            answer = String.format("%.2f", result);
            resultField.setText(answer);
        }
        else if (operation == "-") {
            result = first - second;
            answer = String.format("%.2f", result);
            resultField.setText(answer);
        }
        else if (operation == "/"){
            result = first / second;
            answer = String.format("%.2f", result);
            resultField.setText(answer);
        }
        else if(operation == "*"){
            result = first * second;
            answer = String.format("%.2f", result);
            resultField.setText(answer);
        }
        else if(operation == "%"){
            result = first % second;
            answer = String.format("%.2f", result);
            resultField.setText(answer);
        }
        else if(operation == "X^Y"){
            double resultj = 1;
            for(int i=0; i<second; i++){
                resultj = first * resultj;
            }
            answer=String.format("%.2f", resultj);
            resultField.setText(answer);
        }
        
    }//GEN-LAST:event_equalSignActionPerformed

    private void plusOrminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusOrminusActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(String.valueOf(resultField.getText()));
        a = a*(-1);
        resultField.setText(String.valueOf(a));
        
    }//GEN-LAST:event_plusOrminusActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num0.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num0ActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void divisionSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionSignActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(resultField.getText());
        resultField.setText("");
        operation="/";
    }//GEN-LAST:event_divisionSignActionPerformed

    private void factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(resultField.getText());
        double fact = 1;
        while(a!=0){
            fact = fact * a;
            a--;
        }
        resultField.setText("");
        resultField.setText(resultField.getText()+fact);
    }//GEN-LAST:event_factorialActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num1.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num2.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        String number = resultField.getText()+num3.getText();
        resultField.setText(number);
    }//GEN-LAST:event_num3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        num0.setEnabled(true);
        num1.setEnabled(true);
        num2.setEnabled(true);
        num3.setEnabled(true);
        num4.setEnabled(true);
        num5.setEnabled(true);
        num6.setEnabled(true);
        num7.setEnabled(true);
        num8.setEnabled(true);
        num9.setEnabled(true);
        logarithm.setEnabled(true);
        multiplicationSign.setEnabled(true);
        BackSpace.setEnabled(true);
        Cosinis.setEnabled(true);
        Sinis.setEnabled(true);
        TanOfh.setEnabled(true);
        additionSign.setEnabled(true);
        clearButton.setEnabled(true);
        cosinOfh.setEnabled(true);
        divisionSign.setEnabled(true);
        dot.setEnabled(true);
        eExponent.setEnabled(true);
        equalSign.setEnabled(true);
        factorial.setEnabled(true);
        oneOverx.setEnabled(true);
        percentgButton.setEnabled(true);
        plusOrminus.setEnabled(true);
        resultField.setEnabled(true);
        root.setEnabled(true);
        sinOfh.setEnabled(true);
        substractionSign.setEnabled(true);
        tangent.setEnabled(true);
        xPower2.setEnabled(true);
        xPower3.setEnabled(true);
        xPowery.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        resultField.setText(null);
        num0.setEnabled(false);
        num1.setEnabled(false);
        num2.setEnabled(false);
        num3.setEnabled(false);
        num4.setEnabled(false);
        num5.setEnabled(false);
        num6.setEnabled(false);
        num7.setEnabled(false);
        num8.setEnabled(false);
        num9.setEnabled(false);
        logarithm.setEnabled(false);
        multiplicationSign.setEnabled(false);
        BackSpace.setEnabled(false);
        Cosinis.setEnabled(false);
        Sinis.setEnabled(false);
        TanOfh.setEnabled(false);
        additionSign.setEnabled(false);
        clearButton.setEnabled(false);
        cosinOfh.setEnabled(false);
        divisionSign.setEnabled(false);
        dot.setEnabled(false);
        eExponent.setEnabled(false);
        equalSign.setEnabled(false);
        factorial.setEnabled(false);
        oneOverx.setEnabled(false);
        percentgButton.setEnabled(false);
        plusOrminus.setEnabled(false);
        resultField.setEnabled(false);
        root.setEnabled(false);
        sinOfh.setEnabled(false);
        substractionSign.setEnabled(false);
        tangent.setEnabled(false);
        xPower2.setEnabled(false);
        xPower3.setEnabled(false);
        xPowery.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void percentgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentgButtonActionPerformed
        // TODO add your handling code here:
        first = Double.parseDouble(resultField.getText());
        resultField.setText("");
        operation="+";
    }//GEN-LAST:event_percentgButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyScCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyScCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyScCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyScCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyScCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackSpace;
    private javax.swing.JButton Cosinis;
    private javax.swing.JButton Sinis;
    private javax.swing.JButton TanOfh;
    private javax.swing.JButton additionSign;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton cosinOfh;
    private javax.swing.JButton divisionSign;
    private javax.swing.JButton dot;
    private javax.swing.JButton eExponent;
    private javax.swing.JButton equalSign;
    private javax.swing.JButton factorial;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton logarithm;
    private javax.swing.JButton multiplicationSign;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton oneOverx;
    private javax.swing.JButton percentgButton;
    private javax.swing.JButton plusOrminus;
    private javax.swing.JTextField resultField;
    private javax.swing.JButton root;
    private javax.swing.JButton sinOfh;
    private javax.swing.JButton substractionSign;
    private javax.swing.JButton tangent;
    private javax.swing.JButton xPower2;
    private javax.swing.JButton xPower3;
    private javax.swing.JButton xPowery;
    // End of variables declaration//GEN-END:variables
}
