/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.jdbc.PreparedStatement;
import controller.ClientDao;
import java.awt.Image;
import java.io.File;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Client;
import java.sql.*;
import java.text.MessageFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.ConnectionToDb;

/**
 *
 * @author hirwa
 */
public class clientForm extends javax.swing.JInternalFrame {
    public Connection con = null;
    public ResultSet rs = null;
    public PreparedStatement ps = null;
    public Statement s = null;
    DefaultTableModel model;
    /**
     * Creates new form clientForm
     */
    public clientForm() {
        initComponents();
        updateTableClient();   
    }
    
    public void updateTableClient(){
    model = (DefaultTableModel) clientTable.getModel();
        List<Client> all = new ClientDao().findAll();
        for (Client client : all) {
            model.insertRow(model.getRowCount(), new Object[]{
                
                client.getRegNo(),
                client.getFirstName(),
                client.getLastName(),
                client.getPhoneNUmber(),
                client.getEmailAddress(),
                client.getPhoto(),
                client.getClientCategory(),
            });
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        regNoField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        emailAddressField = new javax.swing.JTextField();
        photoField = new javax.swing.JTextField();
        clientCategoryField = new javax.swing.JComboBox<>();
        saveButtonClient = new javax.swing.JButton();
        resetButtonClient = new javax.swing.JButton();
        updateButtonClient = new javax.swing.JButton();
        printButtonClient = new javax.swing.JButton();
        deleteButtonClient = new javax.swing.JButton();
        exitButtonClient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        Message = new javax.swing.JLabel();
        addImageButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setTitle("Client");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("CLIENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 23, -1, -1));

        jLabel2.setText("Registration Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 87, -1, -1));

        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setText("Photo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 151, -1, -1));

        jLabel6.setText("Emaill Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 109, -1, -1));

        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 67, -1, -1));

        jLabel8.setText("Client Category");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 193, -1, -1));

        regNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regNoFieldKeyReleased(evt);
            }
        });
        getContentPane().add(regNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 87, 160, -1));
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, -1));

        lastNameField.setText(" ");
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, -1));
        getContentPane().add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 64, 145, -1));
        getContentPane().add(emailAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 106, 144, -1));
        getContentPane().add(photoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 148, 70, -1));

        clientCategoryField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Staff" }));
        getContentPane().add(clientCategoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 190, 142, -1));

        saveButtonClient.setText("SAVE");
        saveButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(saveButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 240, -1, -1));

        resetButtonClient.setText("RESET");
        resetButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(resetButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 240, -1, -1));

        updateButtonClient.setText("UPDATE");
        updateButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(updateButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 240, -1, -1));

        printButtonClient.setText("PRINT");
        printButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(printButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 240, -1, -1));

        deleteButtonClient.setText("DELETE");
        deleteButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 240, -1, -1));

        exitButtonClient.setText("EXIT");
        exitButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonClientActionPerformed(evt);
            }
        });
        getContentPane().add(exitButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 240, -1, -1));

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration Number", "FirstName", "Last Name", "Phone Number", "Email Address", "Photo", "Client Category"
            }
        ));
        clientTable.setShowHorizontalLines(false);
        clientTable.setShowVerticalLines(false);
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 299, 601, 144));

        Message.setForeground(new java.awt.Color(238, 236, 236));
        Message.setText(" ");
        getContentPane().add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 20, -1));

        addImageButton.setText("Add");
        addImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 70, -1));
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 110, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonClientActionPerformed
        
        String regNo = regNoField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String phoneNumber = phoneNumberField.getText();
        String emailAddress = emailAddressField.getText();
        String photo = photoField.getText();
        String clientCategory = (String)clientCategoryField.getSelectedItem();
        
        Client cl = new Client(regNo, firstName, lastName, phoneNumber, emailAddress, photo, clientCategory);
        
        ClientDao cld = new ClientDao();
        cld.save(cl);
        
        updateTableClient();
        JOptionPane.showMessageDialog(this, "Successfully saved Client info!!");
    }//GEN-LAST:event_saveButtonClientActionPerformed
    //private JFrame frame;
    private void exitButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonClientActionPerformed
      JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit!!","Client Form",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
        
        
    }//GEN-LAST:event_exitButtonClientActionPerformed

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)clientTable.getModel();
        int selectedRows = clientTable.getSelectedRow();
        
        regNoField.setText(model.getValueAt(selectedRows, 0).toString());
        firstNameField.setText(model.getValueAt(selectedRows, 1).toString());
        lastNameField.setText(model.getValueAt(selectedRows, 2).toString());
        phoneNumberField.setText(model.getValueAt(selectedRows, 3).toString());
        emailAddressField.setText(model.getValueAt(selectedRows, 4).toString());
        photoField.setText(model.getValueAt(selectedRows, 5).toString());       
        String clientCategory = model.getValueAt(selectedRows, 6).toString();
            for(int i=0; i< clientCategoryField.getItemCount(); i++){
                if(clientCategoryField.getItemAt(i).toString().equalsIgnoreCase(clientCategory)){
                clientCategoryField.setSelectedIndex(i);
                }
            }
    }//GEN-LAST:event_clientTableMouseClicked

    private void resetButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonClientActionPerformed
        regNoField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        phoneNumberField.setText("");
        emailAddressField.setText("");
        photoField.setText("");
        clientCategoryField.setSelectedItem(0);
    }//GEN-LAST:event_resetButtonClientActionPerformed

    private void updateButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonClientActionPerformed
        try {
            DefaultTableModel record = (DefaultTableModel)clientTable.getModel();
            int selectedRows = clientTable.getSelectedRow();
            
            int id = Integer.parseInt(record.getValueAt(selectedRows, 0).toString());
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library?","root","");
            s = con.createStatement();
            ps = (PreparedStatement) con.prepareStatement("UPDATE client SET regNo=?, firstName=?, lastName=?, phoneNumber=?, emailAddress=?, photo=?, clientCategory=? WHERE regNo=?");
            
            ps.setString(1, regNoField.getText());
            ps.setString(2, firstNameField.getText());
            ps.setString(3, lastNameField.getText());
            ps.setString(4, phoneNumberField.getText());
            ps.setString(5, emailAddressField.getText());
            ps.setString(6, photoField.getText());
            ps.setString(7, (String)clientCategoryField.getSelectedItem());
            ps.setInt(8, id);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Client Record Successfully updated!!");
            updateTableClient();
            
        } catch (SQLException ex) {
            Logger.getLogger(clientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateButtonClientActionPerformed

    private void deleteButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonClientActionPerformed
        DefaultTableModel model = (DefaultTableModel)clientTable.getModel();
        int SelectedRows = clientTable.getSelectedRow();

        int id = Integer.parseInt(model.getValueAt(SelectedRows, 0).toString());
        int deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete item","Warning",JOptionPane.YES_NO_OPTION);
        if (deleteItem == JOptionPane.YES_OPTION){
            
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","");
                s = con.createStatement();
                ps = (PreparedStatement) con.prepareStatement("DELETE FROM client where regNo=?");
                
                ps.setInt(1, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Client Record updated Successfully!");
                updateTableClient();
                
                regNoField.setText("");
                firstNameField.setText("");
                lastNameField.setText("");
                phoneNumberField.setText("");
                emailAddressField.setText("");
                photoField.setText("");
                clientCategoryField.setSelectedItem(0);
                
            } catch (SQLException ex) {
                Logger.getLogger(clientForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_deleteButtonClientActionPerformed

    private void printButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonClientActionPerformed
        MessageFormat header = new MessageFormat("Printing in Progress...");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");

        try{
            clientTable.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("No printer Found", e.getMessage());
        }
    }//GEN-LAST:event_printButtonClientActionPerformed

    private void regNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regNoFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_regNoFieldKeyReleased

    private void addImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        photoField.setText(filename);
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
        imageLabel.setIcon(icon);
    }//GEN-LAST:event_addImageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JButton addImageButton;
    private javax.swing.JComboBox<String> clientCategoryField;
    private javax.swing.JTable clientTable;
    private javax.swing.JButton deleteButtonClient;
    private javax.swing.JTextField emailAddressField;
    private javax.swing.JButton exitButtonClient;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTextField photoField;
    private javax.swing.JButton printButtonClient;
    private javax.swing.JTextField regNoField;
    private javax.swing.JButton resetButtonClient;
    private javax.swing.JButton saveButtonClient;
    private javax.swing.JButton updateButtonClient;
    // End of variables declaration//GEN-END:variables
}
